import 'package:cloud_firestore/cloud_firestore.dart';

class MockProviderSeeder {
  static Future<void> seedOnce() async {
    final firestore = FirebaseFirestore.instance;
    final collection = firestore.collection('providers');
    
    final providers = [
      {
        'providerId': 'prov1',
        'name': 'Ali Plumber',
        'serviceType': 'Plumbing',
        'rating': 4.8,
        'distanceKm': 2.3,
        'availability': true,
        'basePrice': 1500.0,
        'location': 'DHA Phase 5',
        'reliabilityScore': 95.0,
        'cancellationRate': 2.0,
        'specializations': ['Pipe Burst Repair', 'Drain Cleaning'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov2',
        'name': 'Sara Electrician',
        'serviceType': 'Electrical',
        'rating': 4.9,
        'distanceKm': 3.5,
        'availability': true,
        'basePrice': 800.0,
        'location': 'DHA',
        'reliabilityScore': 98.0,
        'cancellationRate': 1.0,
        'specializations': ['Wiring', 'Appliance Install'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov3',
        'name': 'John Carpenter',
        'serviceType': 'Carpentry',
        'rating': 4.7,
        'distanceKm': 5.1,
        'availability': true,
        'basePrice': 2000.0,
        'location': 'Clifton',
        'reliabilityScore': 92.0,
        'cancellationRate': 4.0,
        'specializations': ['Furniture Assembly', 'Door Repair'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov4',
        'name': 'Ayesha Cleaner',
        'serviceType': 'Cleaning',
        'rating': 5.0,
        'distanceKm': 1.2,
        'availability': true,
        'basePrice': 1000.0,
        'location': 'Gulshan',
        'reliabilityScore': 100.0,
        'cancellationRate': 0.0,
        'specializations': ['Deep Cleaning', 'Sanitization'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov5',
        'name': 'Zain Painter',
        'serviceType': 'Painting',
        'rating': 4.6,
        'distanceKm': 4.8,
        'availability': true,
        'basePrice': 2500.0,
        'location': 'DHA Phase 6',
        'reliabilityScore': 90.0,
        'cancellationRate': 5.0,
        'specializations': ['Wall Painting', 'Waterproofing'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov6',
        'name': 'Fatima AC Repair',
        'serviceType': 'AC Repair',
        'rating': 4.9,
        'distanceKm': 6.2,
        'availability': true,
        'basePrice': 1800.0,
        'location': 'Clifton',
        'reliabilityScore': 96.0,
        'cancellationRate': 3.0,
        'specializations': ['Gas Refill', 'General Service'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov7',
        'name': 'Bilal Handyman',
        'serviceType': 'General',
        'rating': 4.5,
        'distanceKm': 7.0,
        'availability': false,
        'basePrice': 600.0,
        'location': 'Saddar',
        'reliabilityScore': 88.0,
        'cancellationRate': 8.0,
        'specializations': ['Hanging Pictures', 'Minor Fixes'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov8',
        'name': 'Hira Electrician',
        'serviceType': 'Electrical',
        'rating': 4.8,
        'distanceKm': 4.1,
        'availability': true,
        'basePrice': 900.0,
        'location': 'Tariq Road',
        'reliabilityScore': 94.0,
        'cancellationRate': 2.0,
        'specializations': ['UPS Repair', 'Short Circuit Fix'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov9',
        'name': 'Omar Plumber',
        'serviceType': 'Plumbing',
        'rating': 4.7,
        'distanceKm': 2.9,
        'availability': true,
        'basePrice': 1300.0,
        'location': 'Gulshan',
        'reliabilityScore': 93.0,
        'cancellationRate': 3.0,
        'specializations': ['Geyser Fix', 'Tap Leaks'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov10',
        'name': 'Sana Cleaner',
        'serviceType': 'Cleaning',
        'rating': 4.9,
        'distanceKm': 3.0,
        'availability': true,
        'basePrice': 1100.0,
        'location': 'DHA Phase 2',
        'reliabilityScore': 97.0,
        'cancellationRate': 1.0,
        'specializations': ['Sofa Cleaning', 'Kitchen Cleaning'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov11',
        'name': 'Tariq Carpenter',
        'serviceType': 'Carpentry',
        'rating': 4.6,
        'distanceKm': 5.5,
        'availability': true,
        'basePrice': 1900.0,
        'location': 'Clifton',
        'reliabilityScore': 90.0,
        'cancellationRate': 5.0,
        'specializations': ['Lock Repair', 'Cabinet Repair'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov12',
        'name': 'Rabia Painter',
        'serviceType': 'Painting',
        'rating': 4.8,
        'distanceKm': 2.1,
        'availability': true,
        'basePrice': 2400.0,
        'location': 'DHA',
        'reliabilityScore': 95.0,
        'cancellationRate': 2.0,
        'specializations': ['Exterior Painting', 'Wood Polish'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov13',
        'name': 'Usman AC Repair',
        'serviceType': 'AC Repair',
        'rating': 4.7,
        'distanceKm': 4.6,
        'availability': true,
        'basePrice': 1700.0,
        'location': 'Gulshan',
        'reliabilityScore': 91.0,
        'cancellationRate': 4.0,
        'specializations': ['Leakage Fix', 'AC Install'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov14',
        'name': 'Nadia Handyman',
        'serviceType': 'General',
        'rating': 4.8,
        'distanceKm': 8.2,
        'availability': true,
        'basePrice': 700.0,
        'location': 'Saddar',
        'reliabilityScore': 96.0,
        'cancellationRate': 2.0,
        'specializations': ['Assembly', 'Odd Jobs'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov15',
        'name': 'Aliya Plumber',
        'serviceType': 'Plumbing',
        'rating': 4.9,
        'distanceKm': 3.3,
        'availability': true,
        'basePrice': 1600.0,
        'location': 'Tariq Road',
        'reliabilityScore': 98.0,
        'cancellationRate': 1.0,
        'specializations': ['Sanitary Fittings', 'Pipeline Work'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov16',
        'name': 'Kamil Plumber',
        'serviceType': 'Plumbing',
        'rating': 4.5,
        'distanceKm': 6.0,
        'availability': false,
        'basePrice': 1100.0,
        'location': 'Clifton',
        'reliabilityScore': 88.0,
        'cancellationRate': 6.0,
        'specializations': ['Water Pump Repair'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov17',
        'name': 'Raza Electrician',
        'serviceType': 'Electrical',
        'rating': 4.7,
        'distanceKm': 1.8,
        'availability': true,
        'basePrice': 850.0,
        'location': 'DHA Phase 5',
        'reliabilityScore': 92.0,
        'cancellationRate': 4.0,
        'specializations': ['Fan Install', 'DB Repair'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov18',
        'name': 'Basit Carpenter',
        'serviceType': 'Carpentry',
        'rating': 4.8,
        'distanceKm': 3.7,
        'availability': true,
        'basePrice': 2100.0,
        'location': 'Gulshan',
        'reliabilityScore': 94.0,
        'cancellationRate': 3.0,
        'specializations': ['Polishing', 'Sofa Frame repair'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov19',
        'name': 'Noman Cleaner',
        'serviceType': 'Cleaning',
        'rating': 4.6,
        'distanceKm': 5.9,
        'availability': true,
        'basePrice': 950.0,
        'location': 'Saddar',
        'reliabilityScore': 89.0,
        'cancellationRate': 5.0,
        'specializations': ['Carpet Cleaning'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov20',
        'name': 'Farhan Painter',
        'serviceType': 'Painting',
        'rating': 4.9,
        'distanceKm': 4.0,
        'availability': true,
        'basePrice': 2600.0,
        'location': 'Tariq Road',
        'reliabilityScore': 97.0,
        'cancellationRate': 1.0,
        'specializations': ['Texture Painting'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov21',
        'name': 'Yasir AC Repair',
        'serviceType': 'AC Repair',
        'rating': 4.8,
        'distanceKm': 2.5,
        'availability': true,
        'basePrice': 1750.0,
        'location': 'DHA',
        'reliabilityScore': 93.0,
        'cancellationRate': 3.0,
        'specializations': ['Inverter AC Fix'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov22',
        'name': 'Asad Plumber',
        'serviceType': 'Plumbing',
        'rating': 4.6,
        'distanceKm': 5.0,
        'availability': true,
        'basePrice': 1400.0,
        'location': 'DHA Phase 6',
        'reliabilityScore': 91.0,
        'cancellationRate': 4.0,
        'specializations': ['Sanitary Install'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov23',
        'name': 'Sameer Electrician',
        'serviceType': 'Electrical',
        'rating': 4.9,
        'distanceKm': 3.2,
        'availability': true,
        'basePrice': 950.0,
        'location': 'Gulshan',
        'reliabilityScore': 96.0,
        'cancellationRate': 2.0,
        'specializations': ['AC Wiring', 'Lightings'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov24',
        'name': 'Waqas Carpenter',
        'serviceType': 'Carpentry',
        'rating': 4.5,
        'distanceKm': 7.5,
        'availability': false,
        'basePrice': 1800.0,
        'location': 'Saddar',
        'reliabilityScore': 87.0,
        'cancellationRate': 7.0,
        'specializations': ['Wood Partition'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov25',
        'name': 'Tahira Cleaner',
        'serviceType': 'Cleaning',
        'rating': 4.7,
        'distanceKm': 4.3,
        'availability': true,
        'basePrice': 1050.0,
        'location': 'Clifton',
        'reliabilityScore': 92.0,
        'cancellationRate': 3.0,
        'specializations': ['Window cleaning'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov26',
        'name': 'Shakir Painter',
        'serviceType': 'Painting',
        'rating': 4.8,
        'distanceKm': 3.9,
        'availability': true,
        'basePrice': 2300.0,
        'location': 'Gulshan',
        'reliabilityScore': 94.0,
        'cancellationRate': 2.0,
        'specializations': ['Wall Putty'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov27',
        'name': 'Zeeshan AC Repair',
        'serviceType': 'AC Repair',
        'rating': 4.9,
        'distanceKm': 1.7,
        'availability': true,
        'basePrice': 2000.0,
        'location': 'PECHS',
        'reliabilityScore': 96.0,
        'cancellationRate': 2.0,
        'specializations': ['AC leak fix'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov28',
        'name': 'Imran Plumber',
        'serviceType': 'Plumbing',
        'rating': 4.7,
        'distanceKm': 2.2,
        'availability': true,
        'basePrice': 1350.0,
        'location': 'PECHS',
        'reliabilityScore': 92.0,
        'cancellationRate': 3.0,
        'specializations': ['Bathroom Fittings'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov29',
        'name': 'Fahad Electrician',
        'serviceType': 'Electrical',
        'rating': 4.8,
        'distanceKm': 3.0,
        'availability': true,
        'basePrice': 1000.0,
        'location': 'PECHS',
        'reliabilityScore': 94.0,
        'cancellationRate': 2.0,
        'specializations': ['Solar wiring'],
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'providerId': 'prov30',
        'name': 'Farida Cleaner',
        'serviceType': 'Cleaning',
        'rating': 4.6,
        'distanceKm': 4.9,
        'availability': true,
        'basePrice': 1150.0,
        'location': 'PECHS',
        'reliabilityScore': 90.0,
        'cancellationRate': 4.0,
        'specializations': ['Vacuum cleaning'],
        'createdAt': FieldValue.serverTimestamp(),
      }
    ];

    for (final provider in providers) {
      await collection.doc(provider['providerId'] as String).set(provider);
    }
    print('Successfully seeded 30 providers with locations.');
  }
}
