import 'package:cloud_firestore/cloud_firestore.dart';

class MockProviderSeeder {
  static Future<void> seedOnce() async {
    final firestore = FirebaseFirestore.instance;
    final collection = firestore.collection('providers');
    
    final providers = [
      {
        'id': 'prov1',
        'name': 'Ali Plumber',
        'service': 'Plumbing',
        'rating': 4.8,
        'location_area': 'DHA Phase 5',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov2',
        'name': 'Sara Electrician',
        'service': 'Electrical',
        'rating': 4.9,
        'location_area': 'DHA',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov3',
        'name': 'John Carpenter',
        'service': 'Carpentry',
        'rating': 4.7,
        'location_area': 'Clifton',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov4',
        'name': 'Ayesha Cleaner',
        'service': 'Cleaning',
        'rating': 5.0,
        'location_area': 'Gulshan',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov5',
        'name': 'Zain Painter',
        'service': 'Painting',
        'rating': 4.6,
        'location_area': 'DHA Phase 6',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov6',
        'name': 'Fatima AC Repair',
        'service': 'AC Repair',
        'rating': 4.9,
        'location_area': 'Clifton',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov7',
        'name': 'Bilal Handyman',
        'service': 'General',
        'rating': 4.5,
        'location_area': 'Saddar',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov8',
        'name': 'Hira Electrician',
        'service': 'Electrical',
        'rating': 4.8,
        'location_area': 'Tariq Road',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov9',
        'name': 'Omar Plumber',
        'service': 'Plumbing',
        'rating': 4.7,
        'location_area': 'Gulshan',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov10',
        'name': 'Sana Cleaner',
        'service': 'Cleaning',
        'rating': 4.9,
        'location_area': 'DHA Phase 2',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov11',
        'name': 'Tariq Carpenter',
        'service': 'Carpentry',
        'rating': 4.6,
        'location_area': 'Clifton',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov12',
        'name': 'Rabia Painter',
        'service': 'Painting',
        'rating': 4.8,
        'location_area': 'DHA',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov13',
        'name': 'Usman AC Repair',
        'service': 'AC Repair',
        'rating': 4.7,
        'location_area': 'Gulshan',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov14',
        'name': 'Nadia Handyman',
        'service': 'General',
        'rating': 4.8,
        'location_area': 'Saddar',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov15',
        'name': 'Aliya Plumber',
        'service': 'Plumbing',
        'rating': 4.9,
        'location_area': 'Tariq Road',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov16',
        'name': 'Kamil Plumber',
        'service': 'Plumbing',
        'rating': 4.5,
        'location_area': 'Clifton',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov17',
        'name': 'Raza Electrician',
        'service': 'Electrical',
        'rating': 4.7,
        'location_area': 'DHA Phase 5',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov18',
        'name': 'Basit Carpenter',
        'service': 'Carpentry',
        'rating': 4.8,
        'location_area': 'Gulshan',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov19',
        'name': 'Noman Cleaner',
        'service': 'Cleaning',
        'rating': 4.6,
        'location_area': 'Saddar',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov20',
        'name': 'Farhan Painter',
        'service': 'Painting',
        'rating': 4.9,
        'location_area': 'Tariq Road',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov21',
        'name': 'Yasir AC Repair',
        'service': 'AC Repair',
        'rating': 4.8,
        'location_area': 'DHA',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov22',
        'name': 'Asad Plumber',
        'service': 'Plumbing',
        'rating': 4.6,
        'location_area': 'DHA Phase 6',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov23',
        'name': 'Sameer Electrician',
        'service': 'Electrical',
        'rating': 4.9,
        'location_area': 'Gulshan',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov24',
        'name': 'Waqas Carpenter',
        'service': 'Carpentry',
        'rating': 4.5,
        'location_area': 'Saddar',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov25',
        'name': 'Tahira Cleaner',
        'service': 'Cleaning',
        'rating': 4.7,
        'location_area': 'Clifton',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov26',
        'name': 'Shakir Painter',
        'service': 'Painting',
        'rating': 4.8,
        'location_area': 'Gulshan',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov27',
        'name': 'Zeeshan AC Repair',
        'service': 'AC Repair',
        'rating': 4.9,
        'location_area': 'PECHS',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov28',
        'name': 'Imran Plumber',
        'service': 'Plumbing',
        'rating': 4.7,
        'location_area': 'PECHS',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov29',
        'name': 'Fahad Electrician',
        'service': 'Electrical',
        'rating': 4.8,
        'location_area': 'PECHS',
        'createdAt': FieldValue.serverTimestamp(),
      },
      {
        'id': 'prov30',
        'name': 'Farida Cleaner',
        'service': 'Cleaning',
        'rating': 4.6,
        'location_area': 'PECHS',
        'createdAt': FieldValue.serverTimestamp(),
      }
    ];

    for (final provider in providers) {
      await collection.doc(provider['id'] as String).set(provider);
    }
    print('Successfully seeded 30 providers with locations.');
  }
}
