// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR9lT_xmTafXJ8MrDKWRFbhgdsG7H3KRg',
    appId: '1:725655021325:web:cfbb4e8f8eb4afb9193244',
    messagingSenderId: '725655021325',
    projectId: 'boldo-e1db4',
    authDomain: 'boldo-e1db4.firebaseapp.com',
    storageBucket: 'boldo-e1db4.firebasestorage.app',
    measurementId: 'G-Y7TNY3CH9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg_6Sn5UGEFL4kSiy3YYfnASKCPFCPcNk',
    appId: '1:725655021325:android:14d2585452361570193244',
    messagingSenderId: '725655021325',
    projectId: 'boldo-e1db4',
    storageBucket: 'boldo-e1db4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8P9U3IORGXAHYJ8YoY1HYInbjiXc1LZU',
    appId: '1:725655021325:ios:a239bf504f1a4f06193244',
    messagingSenderId: '725655021325',
    projectId: 'boldo-e1db4',
    storageBucket: 'boldo-e1db4.firebasestorage.app',
    iosBundleId: 'com.example.boldoAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8P9U3IORGXAHYJ8YoY1HYInbjiXc1LZU',
    appId: '1:725655021325:ios:a239bf504f1a4f06193244',
    messagingSenderId: '725655021325',
    projectId: 'boldo-e1db4',
    storageBucket: 'boldo-e1db4.firebasestorage.app',
    iosBundleId: 'com.example.boldoAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR9lT_xmTafXJ8MrDKWRFbhgdsG7H3KRg',
    appId: '1:725655021325:web:d8311916bb1d3065193244',
    messagingSenderId: '725655021325',
    projectId: 'boldo-e1db4',
    authDomain: 'boldo-e1db4.firebaseapp.com',
    storageBucket: 'boldo-e1db4.firebasestorage.app',
    measurementId: 'G-G0PWMXBKVX',
  );
}
